table SkillByHour
	lineageTag: f8e4a0be-1fb8-4c4b-99ae-e108c150cc6f

	column hour_of_day
		dataType: int64
		sourceColumn: hour_of_day
		lineageTag: 92d74c58-c29d-4314-a3a7-b2015f334a0c

	column hours
		dataType: int64
		sourceColumn: hours
		lineageTag: b5726bec-c89e-4014-a29e-c87d9e921db2

	column skill
		dataType: double
		sourceColumn: skill
		lineageTag: 24b551d1-e24a-49d7-87ba-875dbfb98120

	column avg_actual
		dataType: double
		sourceColumn: avg_actual
		lineageTag: 49b7fccc-d2fa-4673-a9c6-d3a2da56305e

	column verdict
		dataType: string
		sourceColumn: verdict
		lineageTag: da394f6f-d010-413d-9fb8-27c7fee1f655

	partition SkillByHour = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\skill_by_hour.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"hour_of_day", Int64.Type}, {"hours", Int64.Type}, {"skill", type number}, {"avg_actual", type number}, {"verdict", type text}})
				in
				    Typed
